#!/usr/bin/perl

use strict;
use warnings;
use autodie qw( :all );

use Cwd qw( abs_path );
use File::chdir;
use File::Find::Rule;
use File::Path qw( rmtree );
use File::Temp qw( tempdir );
use LWP::Simple qw( getstore );

my $target_dir = abs_path('cldr-data');
-d $target_dir or die 'Cannot find target dir';

my $tempdir = tempdir( CLEANUP => 1 );

my $file = "$tempdir/core.zip";

my $uri = 'http://unicode.org/Public/cldr/latest/core.zip';
#my $uri = 'file:///home/autarch/projects/Locale-CLDR/core.zip';

my $rc = getstore( $uri, $file );

die 'Could not get latest core.zip' unless $rc == 0 || $rc == 200;

{
    local $CWD = $target_dir;
    system( 'unzip', '-qq', $file );
}

for my $dir ( File::Find::Rule->dir()->maxdepth(0)->in($target_dir) ) {
    rmtree($dir);
}

my $mode = 0644;
chmod $mode, $_ for File::Find::Rule->file()->in($target_dir);
